/**
 * Skill Generator
 *
 * 技能生成器，将分析结果转换为标准技能文件
 */

import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import {
  SkillSuggestion,
  GeneratorOptions,
  DraftSkill,
} from './types-precipitation';

/**
 * 生成结果
 */
export interface GenerationResult {
  /** 生成的技能数量 */
  skillsGenerated: number;
  /** 生成的文件路径 */
  filePaths: string[];
  /** 执行时间（毫秒） */
  duration: number;
}

/**
 * 技能生成器
 */
export class SkillGenerator {
  private projectRoot: string;
  private options: GeneratorOptions;

  constructor(projectRoot: string, options: GeneratorOptions) {
    this.projectRoot = projectRoot;
    this.options = options;
  }

  /**
   * 生成技能文件
   */
  async generate(suggestions: SkillSuggestion[]): Promise<GenerationResult> {
    const startTime = Date.now();

    console.log(`[Generator] Generating ${suggestions.length} skill files...`);

    const filePaths: string[] = [];

    for (const suggestion of suggestions) {
      try {
        const filePath = await this.generateOne(suggestion);
        filePaths.push(filePath);
        console.log(`[Generator] ✓ Generated: ${suggestion.name}`);
      } catch (error: any) {
        console.error(`[Generator] ✗ Failed to generate ${suggestion.name}: ${error.message}`);
      }
    }

    const duration = Date.now() - startTime;

    console.log(`[Generator] ✓ Generated ${filePaths.length}/${suggestions.length} skills in ${duration}ms`);

    return {
      skillsGenerated: filePaths.length,
      filePaths,
      duration,
    };
  }

  /**
   * 生成单个技能文件
   */
  async generateOne(suggestion: SkillSuggestion): Promise<string> {
    // 1. 生成技能目录名
    const dirName = this.sanitizeDirName(suggestion.name);
    const targetDir = join(this.options.targetDir, dirName);

    // 2. 创建目录
    await mkdir(targetDir, { recursive: true });

    // 3. 生成 SKILL.md 内容
    const content = this.formatSkillFile(suggestion);

    // 4. 保存文件
    const filePath = join(targetDir, 'SKILL.md');
    await writeFile(filePath, content, 'utf-8');

    // 5. 保存元数据（可选）
    if (this.options.includeMetadata) {
      const metadataPath = join(targetDir, 'metadata.json');
      await writeFile(metadataPath, JSON.stringify(suggestion, null, 2), 'utf-8');
    }

    return filePath;
  }

  /**
   * 格式化技能文件
   */
  private formatSkillFile(suggestion: SkillSuggestion): string {
    // YAML Frontmatter
    const yaml = this.formatYaml(suggestion);

    // Markdown 内容
    const markdown = this.formatMarkdown(suggestion);

    return `${yaml}\n${markdown}`;
  }

  /**
   * 格式化 YAML Frontmatter
   */
  private formatYaml(suggestion: SkillSuggestion): string {
    const lines = ['---'];

    lines.push(`name: ${suggestion.name}`);
    lines.push(`description: ${suggestion.description}`);
    lines.push(`type: ${suggestion.type}`);
    lines.push(`complexity: ${suggestion.complexity}`);

    if (suggestion.tags.length > 0) {
      lines.push(`tags: [${suggestion.tags.map((t) => `"${t}"`).join(', ')}]`);
    }

    lines.push(`confidence: ${suggestion.confidence}`);

    if (suggestion.id) {
      lines.push(`generatedAt: "${suggestion.generatedAt?.toISOString()}"`);
    }

    if (suggestion.evidence.length > 0) {
      lines.push(`evidenceCount: ${suggestion.evidence.length}`);
    }

    // 草稿状态标记
    if (this.options.saveAsDraft) {
      lines.push(`status: draft`);
      lines.push(`autoGenerated: true`);
    }

    lines.push('---');

    return lines.join('\n');
  }

  /**
   * 格式化 Markdown 内容
   */
  private formatMarkdown(suggestion: SkillSuggestion): string {
    const sections: string[] = [];

    // 标题
    sections.push(`# ${suggestion.name}\n`);

    // 概述
    sections.push('## 概述\n');
    sections.push(`${suggestion.description}\n`);

    // 使用场景
    if (suggestion.whenToUse.length > 0) {
      sections.push('## 使用场景\n');
      suggestion.whenToUse.forEach((scenario) => {
        sections.push(`- ${scenario}\n`);
      });
      sections.push('');
    }

    // 核心知识
    sections.push('## 核心知识\n');
    sections.push(`${suggestion.coreKnowledge}\n`);

    // 支持证据
    if (suggestion.evidence.length > 0) {
      sections.push('## 支持证据\n');
      suggestion.evidence.forEach((evidence) => {
        sections.push(`### ${this.formatEvidenceSource(evidence.source)}\n`);
        sections.push(`${evidence.description}\n`);
        sections.push(`**出现次数**: ${evidence.count || 'N/A'}\n`);
        if (evidence.examples.length > 0) {
          sections.push('**示例**:\n');
          evidence.examples.forEach((example) => {
            sections.push(`- \`${example}\`\n`);
          });
        }
        if (evidence.lastSeen) {
          sections.push(`**最后出现**: ${new Date(evidence.lastSeen).toLocaleDateString()}\n`);
        }
        sections.push('');
      });
    }

    // 示例
    if (suggestion.examples.length > 0) {
      sections.push('## 示例\n');
      suggestion.examples.forEach((example, index) => {
        sections.push(`### 示例 ${index + 1}: ${example.scenario}\n`);
        sections.push(`${example.solution}\n`);
        if (example.code) {
          sections.push('**代码**:\n');
          sections.push('```');
          sections.push(example.code);
          sections.push('```\n');
        }
      });
    }

    // 元数据注释（如果是草稿）
    if (this.options.includeMetadata && this.options.saveAsDraft) {
      sections.push('---\n');
      sections.push('## 元数据\n');
      sections.push(`\n<!-- Generated by Newma Precipitation System -->\n`);
      sections.push(`<!-- Confidence: ${(suggestion.confidence * 100).toFixed(1)}% -->\n`);
      sections.push(`<!-- Generated: ${suggestion.generatedAt?.toISOString()} -->\n`);
    }

    return sections.join('\n');
  }

  /**
   * 格式化证据来源名称
   */
  private formatEvidenceSource(source: string): string {
    const names: Record<string, string> = {
      errors: '错误记录',
      history: '执行历史',
      preferences: '用户偏好',
      context: '项目上下文',
      reasoning: '推理过程',
      decisions: '决策记录',
      sessions: '会话历史',
    };
    return names[source] || source;
  }

  /**
   * 清理目录名（移除特殊字符）
   */
  private sanitizeDirName(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50); // 限制长度
  }

  /**
   * 从临时文件加载建议
   */
  async loadSuggestionsFromTemp(tempFilePath: string): Promise<SkillSuggestion[]> {
    const { readFile } = require('fs/promises');
    const content = await readFile(tempFilePath, 'utf-8');
    return JSON.parse(content) as SkillSuggestion[];
  }

  /**
   * 验证技能文件格式
   */
  validateSkillFile(content: string): boolean {
    // 检查 YAML Frontmatter
    const hasFrontmatter = content.startsWith('---');
    if (!hasFrontmatter) return false;

    // 检查必需字段
    const requiredFields = ['name:', 'description:', 'type:'];
    const hasRequiredFields = requiredFields.some((field) => content.includes(field));

    return hasRequiredFields;
  }
}
